### ISSUE TITLE
Bitte die Verbindungsvariablen in eine Properties Datei auslagern+auslesen

### ISSUE THREAD

**Issue by TobiasSMI** [Eyyuep/DBsync#1]
Lagert bitte die Variablen zu Beginn der Main Methode aus -> in eine Properties Datei. 
Lest diese Properties aus der Datei aus, wo es nötig ist und ruft die Inhalte ab.

So werden die Verbindungsdaten auch für andere Programmteile verfügbar gemacht und können an einer zentralen Stelle gepflegt werden.

Beispiele:
https://www.javatpoint.com/properties-class-in-java

https://github.com/Eyyuep/DBsync/blob/4ac7d13a2247aad6a9dfba90f47911bc59cb730a/src/main/java/de/praktikant/Main.java#L15-L21

**Comment by nartesh** [comment]
Daten wurden in eine "properties" Datei ausgelagert und der Commit mit der ID: e98ff247bef3fe8e1201a20b94202454bce5e7bb behebt Issues.
