### ISSUE TITLE
how to solve java.lang.ClassNotFoundException: org.slf4j.LoggerFactory

### ISSUE THREAD

**Issue by Eyyuep** [Eyyuep/DBsync#10]
Der Befehl ```javac Main.java``` über die CMD-Leiste wirft diesen error aus:

```Main.java:6: error: package org.slf4j does not exist
import org.slf4j.*;
^
Main.java:13: error: cannot find symbol
        Logger logger = LoggerFactory.getLogger(Main.class);
        ^
  symbol:   class Logger
  location: class Main
Main.java:13: error: cannot find symbol
        Logger logger = LoggerFactory.getLogger(Main.class);
                        ^
  symbol:   variable LoggerFactory
  location: class Main

**Comment by FlorianMihm** [comment]
javac -d "AUSGANGSPFAD" -cp "PFAD-ZU-.m2\repository\org\postgresql\postgresql\VERSION\postgresql-VERSION.jar;PFAD-ZU-.m2\repository\org\slf4j\slf4j-api\VERSION\slf4j-api-VERSION.jar;.\src\main\java\de\praktikant\*.java"

Das Großgeschriebene noch ergänzen.

**Comment by FlorianMihm** [comment]
javac -d "AUSGANGSPFAD" -cp "PFAD-ZU-.m2\repository\org\postgresql\postgresql\VERSION\postgresql-VERSION.jar;PFAD-ZU-.m2\repository\org\slf4j\slf4j-api\VERSION\slf4j-api-VERSION.jar;.\src\main\java\de\praktikant\*.java"

Das Großgeschriebene noch ergänzen.

**Comment by nartesh** [comment]
## Zum **KOMPILIEREN** der Dateien diesen Befehl benutzen:

```javac -d .\target\classes\ -cp "C:\Users\Asus\.m2\repository\org\postgresql\postgresql\42.5.0\postgresql-42.5.0.jar;C:\Users\Asus\.m2\repository\org\slf4j\slf4j-api\1.7.30\slf4j-api-1.7.30.jar" .\src\main\java\de\praktikant\*.java```

## Zum **AUSFÜHREN** der Dateien diesen Befehl benutzen:

```java -cp ".\target\classes\;C:\Users\Asus\.m2\repository\org\postgresql\postgresql\42.5.0\postgresql-42.5.0.jar;C:\Users\Asus\.m2\repository\org\slf4j\slf4j-api\1.7.30\slf4j-api-1.7.30.jar;C:\Users\Asus\.m2\repository\org\slf4j\slf4j-simple\1.7.30\slf4j-simple-1.7.30.jar" de.praktikant.Main```
<br>
Dieser cmd Befehl hat funktioniert. Danke! @FlorianMihm
