### ISSUE TITLE
Bitte alle Klassennamen überarbeiten

### ISSUE THREAD

**Issue by TobiasSMI** [Eyyuep/DBsync#11]
https://github.com/Eyyuep/DBsync/blob/43982a4de896440158e121eec18b291355ba6116/src/main/java/de/praktikant/compareData.java#L6

siehe: https://google.github.io/styleguide/javaguide.html#s5.2.2-class-names

**Comment by nartesh** [comment]
@TobiasSMI, die Klassennamen wurden umbenannt.

Ein Beispiel hier:
![Screenshot 2022-11-30 101241](https://user-images.githubusercontent.com/74494162/204755134-9d5a8dc8-b050-4b80-93a7-1a351a4b6b2e.png)
