### ISSUE TITLE
Erstellung und Übertrag nach Spring Boot

### ISSUE THREAD

**Issue by nartesh** [Eyyuep/DBsync#12]
Das Maven Projekt war der working Prototype jedoch soll die finale Version in Spring Boot stattfinden.

- [x] #23
- [x] #24
- [x] #25
- [x] #26

- [x] #27

**Comment by TobiasSMI** [comment]
Falls ihr die Info nicht erhalten habt, hier noch einmal die Mail, die ich Leon habe zukommen lassen. Diese hätte eigentlich schon längst als Issue auf dem Plan stehen sollen.


> Von: Smialkowski, Tobias 
> Gesendet: Montag, 28. November 2022 11:03
> An: 'Leon Steger' <leon.steger92@gmail.com>
> Betreff: AW: Update
> 
> Noch ein Hinweis, schaut bitte, dass ihr das Projekt als ein Spring Boot Projekt erzeugt, über diese Website, und eure Komponente dann dort einbettet:
> 
> https://start.spring.io/
> 
> Macht euch wegen der Dependencies keine Sorgen, die könnt ihr nachträglich über die pom.xml einpflegen.
> 
> Das wird deutlich einfacher sein, als das Projekt nachträglich nach Spring zu übertragen. (Bitte auch auf die Unterscheidung Spring / Spring Boot achten!)
> 
> Viele Grüße
> Tobias
