### ISSUE TITLE
 Code formatieren

### ISSUE THREAD

**Issue by Gromidev** [Eyyuep/DBsync#13]
Vorhandenen Code Kommentieren und formatieren.
Ordnung einhalten und die Beispiele für guten Code beachten.

**Comment by TobiasSMI** [comment]
Moin @Gromidev ,
liest sich gut, für ein Issue würde ich empfehlen konkrete Stellen in die Aufgabe aufzunehmen, um die sich die Beteiligten kümmern können (wenn es sich auf den Code bezieht)

![chrome_nuMDBNahDe](https://user-images.githubusercontent.com/41923750/204769245-b5e18652-8af6-4f43-9bc6-e70289577dfb.gif)


In diesem Fall könnte man z.B. auf konkrete Missachtungen hindeuten, die zu beheben sind. Die Aufgabe würde sonst auf ewig "unerledigt" bleiben, da sie nicht S.M.A.R.T gestellt ist.

Beispiel
- [x] Klassennamen sind teils klein geschrieben. Bitte bis Freitag den 02.12. überarbeiten.

**Comment by Gromidev** [comment]
@TobiasSMI Woher weiß ich welche Missachtungen stattfinden? Bevor Florian uns das heute erklärt hat hatte ich das Problem mit kleingeschriebenen Klassennamen grade nicht vorne im Gedächnis und als eine art der Schreibweise (CamelCase/snake_cae etc.) betrachtet. Kann dann ein Issue einfach sein das alle den Code reviewen und eigene Issues anlegen wenn ihnen ein Fehler auffällt (ich natürlich auch)?

**Comment by TobiasSMI** [comment]
@Gromidev das kommt mit mehr Erfahrung ganz automatisch. Ich wollte darauf hinaus, dass ein Issue, welches 
> Vorhandenen Code Kommentieren und formatieren.
> Ordnung einhalten und die Beispiele für guten Code beachten.

vorgibt, zu allgemein gehalten ist. Woran misst der Entwickler, dass dieses Ticket nun erledigt ist, wann darf er es erledigen? Hierfür bitte die [SMART ](https://boardview.io/blog/get-smart-in-defining-smart-goals/#:~:text=No%20more%20discussions.-,What%20does%20the%20SMART%20acronym%20stand%20for%3F,-In%201981%20a)Zielsetzung für ein Issue beachten.

Du kannst Issues für jede noch so kleinteilige Aufgabe anlegen, die erst einmal aufgeschoben wird. Diese können dann priorisiert und in eine sinnvolle Reihenfolge zur Abarbeitung gebracht und leicht an die Kollegen delegiert werden.

Allgemein gilt:
> Nur, was man aufschreibt, vergisst man nicht und kann man effektiv delegieren und verfolgen.

siehe: https://clean-code-developer.de/die-grade/orangener-grad/#Issue_Tracking:~:text=Praktiken-,Issue%20Tracking,-Warum%3F%0ANur

**Comment by nartesh** [comment]
@TobiasSMI, die Klassennamen sind fertig seit gestern, aber nur in dev Branche. Wenn wir noch Formatierungsfehler finden, dann erzeugen wir neue Issues.
