### ISSUE TITLE
Datenbanken und Tabellen als String Variablen gespeichert

### ISSUE THREAD

**Issue by nartesh** [Eyyuep/DBsync#17]
@TobiasSMI, die Datenbanken mit der Tabellen haben wir in Variablen gespeichert, aber wir wussten nicht, ob das richtig ist.

https://github.com/Eyyuep/DBsync/blob/b430a7e3006886385efc8c0a5b1bd3d072bd8c60/src/main/java/de/praktikant/Start.java#L20

**Comment by TobiasSMI** [comment]
Hallo @nartesh ,
super, sieht sehr gut aus. Ich empfehle noch eine kleine Anpassung an den Variablen Namen.

Es könnte Sinn machen, den Tabellen eindeutigere Namen als "db_tbl1" und "db_tbl2" zu geben. Gebt eine der Tabellen einen Bezeichner das klar ist, Tabelle1 ist unsere Referenz Tabelle, an dieser wollen wir uns ausrichten, deren Werte sehen wir als Single Source of Truth. Tabelle2 ist daher für euch die... "Vergleichstabelle". In dieser Tabelle vermutet ihr Abweichungen gegenüber der Referenz.

Wählt daher bitte sprechende Namen für die beiden Tabellen, das o.g. ist nur eine kurze Erläuterung, wieso ich das für Sinnvoll halte.

**Comment by TobiasSMI** [comment]
Die Änderung der Variablennamen darf gerne über diese Issue behandelt werden und erfordert kein neues Issue. Sollten ihr das anders sehen, steht es euch natürlich frei, einen neuen Vorgang für diesen Änderungswunsch zu erzeugen.

**Comment by Eyyuep** [comment]
@TobiasSMI wir haben deinen Vorschlag umgesetzt 340f392d3a7ecc8c3449e15d6257ba694c2f7ddb
