### ISSUE TITLE
Aufräumen von unbenutzten "imports" in jeder Klasse

### ISSUE THREAD

**Issue by nartesh** [Eyyuep/DBsync#18]
https://github.com/Eyyuep/DBsync/blob/b430a7e3006886385efc8c0a5b1bd3d072bd8c60/src/main/java/de/praktikant/Start.java#L3

@TobiasSMI, oben ist nur ein Beispiel für die import (in unseren Fall mit *).

**Comment by TobiasSMI** [comment]
Mit der richtigen IDE solltet ihr direkt Vorschläge sehen können, hier mal ein Beispiel aus VSCode:

![image](https://user-images.githubusercontent.com/41923750/205045376-ac199c64-c348-410e-8176-0e3306b06c5d.png)

Anschließend müsst ihr nur noch im Reiter "Probleme" diese beheben.

**Comment by TobiasSMI** [comment]
Noch ein Tipp: mit dem * ladet ihr ALLE Klassen eines Paketes. Das sollte nicht passieren, löst dieses * auf und importiert lediglich die benötigten Klassen aus dem SQL Paket (ja ich weiß, in den Standardpaketen ist das nicht so wild, aber es sollte zur Gewohnheit werden _**nur das nötigste zu importieren**_)

Bitte macht dazu ein neues Issue, in dem ihr euch alle Imports vornehmt mit einem * am Ende.

**Comment by nartesh** [comment]
@TobiasSMI, Issue wurde erstellt. Danke für Tipps!
