### ISSUE TITLE
Bitte nutzt einen logger, statt eurer SysOuts

### ISSUE THREAD

**Issue by TobiasSMI** [Eyyuep/DBsync#2]
ich nutze dabei ganz gerne slf4j
**Ziel ist es, alle System.out.prints gegen log.info() auszutauschen.**

Hier ein Beispiel, wie der Logger aufgerufen wird
https://sematext.com/blog/slf4j-tutorial/

Schaut euch in dem Zuge bitte auch alle "loglevels" an und wann welche Loglevel eingesetzt werden:
https://www.javatpoint.com/java-logger#:~:text=%7D-,Java%20Logging%20Levels,-It%20shows%20the

**Comment by nartesh** [comment]
Wir haben recherchiert und versucht zu machen, aber etwas nicht klappen

![Screenshot 2022-11-22 155042](https://user-images.githubusercontent.com/74494162/203345514-fe273bb0-c0ba-4c73-bf2e-c309a0c563c0.png)

**Comment by TobiasSMI** [comment]
Ich schaue morgen mal drauf.

**Comment by nartesh** [comment]
System.out.print ersetzt durch logger.info und logger.warn
