### ISSUE TITLE
Lauffähigkeit prüfen

### ISSUE THREAD

**Issue by Eyyuep** [Eyyuep/DBsync#25]
Bisher wurden zwei Datenbanken mit jeweils **100 Datensätze** miteinander verglichen und jetzt werden wir das Ganze nochmal überprüfen um die Lauffähigkeit zu analysieren: <br>
- [ ] 10.000   Datensätzen
- [ ] 50.000   Datensätzen
- [ ] 100.000 Datensätzen

**Comment by TobiasSMI** [comment]
ich bin gespannt auf die Ergebnisse. Bitte auch für 50k und 100k Einträge prüfen (wir haben nämlich bereits jetzt > 50.000 Vorgänge, die Zahlen sind also durchaus realistisch.

Ggf. müsst ihr euren Algorithmus optimieren um die Performance zu verbessern (falls eure Tests schlecht ausfallen)

**Comment by Eyyuep** [comment]
Hier eine Ausgabe mit 100.000 Datensätzen mit gewollten fehlern in der Vergleichstabelle.

![grafik](https://user-images.githubusercontent.com/115067739/205882248-3e42c029-b3e1-4f4c-a2a0-dd4e39f95ac7.png)
**...**

![grafik](https://user-images.githubusercontent.com/115067739/205882606-622b4381-a552-4f80-ab7e-0f726685592e.png)

Wir haben jeweils die Datenbanken mit 10.000, 50.000 und 100.000 Datensätze gefüllt und das Programm getestet mit diesen Spec´s **(Win11, AMD Ryzen 5, 16 GB RAM)**. Die Tests haben ergeben, dass das Progamm unter 2-3 Sekunden zum ausführen und ausgeben braucht.
