### ISSUE TITLE
Exception richtig behandeln und loggen

### ISSUE THREAD

**Issue by FlorianMihm** [Eyyuep/DBsync#29]
Die einzelnen Methoden werfen eine Menge unterschiedliche Exception, die nicht weiter behandelt werden:

`private void vergleichDBs() throws FileNotFoundException, IOException, SQLException`

Diese sind aber wichtig, um das Verhalten des Programms zu loggen oder auch um den Nutzer auf Fehler hinzuweisen.
Ein Beispiel wäre das Fehlen der properties-File:

```
FileReader reader = new FileReader("src\\main\\java\\de\\praktikant\\db.config.properties");
Properties p = new Properties();  
p.load(reader); 
```

Fehlt diese, sollte es geloggt und der Hinweis ausgegeben werden. Eventuell auch überlegen, das Programm dann vorzeitig zu beenden, weil das weitere ausführen keinen Sinn mehr hat.

**Comment by Eyyuep** [comment]
@FlorianMihm Ist das schon der richtige Ansatz? falls ja würden wir uns den anderen Exceptions weiter widmen.


https://github.com/Eyyuep/DBsync/blob/d7c6ad0d5634542c1f8649c2845ab3eb9687a773/src/main/java/de/praktikant/Start.java#L28-L37

**Comment by FlorianMihm** [comment]
@Eyyuep Das sieht soweit gut aus. Wichtig ist noch beim catch Block die richtige Exception abzufangen (Exception ist die Oberklasse) und eventuell mit System.Exit(0) das Programm vorzeitig zu beenden.

**Comment by Eyyuep** [comment]
@FlorianMihm  mit dem Commit 9b01be20a98b5812447620796d9b725da777cfbd haben wir schon deine Tipps umgesetzt und würden uns gegebensfalls über weiteren Feedback freuen.

**Comment by FlorianMihm** [comment]
@Eyyuep Perfekt. Aussagekräftige Meldung habt ihr hinterlegt und die richtigen Exception genommen. Das "throws" Schlüsselwort im Methodenkopf wird dann nicht mehr benötigt. Achtet aber darauf, dass noch weitere Methodenaufrufe in euren Methoden Exception werfen.
Habt ihr getestet, ob bei fehlender properties-File oder falschen Datenbank-Daten auch die Fehlermeldung kommt und das Programm beendet wird?

**Comment by Eyyuep** [comment]
@FlorianMihm Vielen Dank für den Hinweis.

Wird nachgeholt und weiter ergänzt.

**Comment by Eyyuep** [comment]
Mit dem Commit b3d9b9d0d9481c5aa908304ec28674057dd60084 wurden deine Erwartung  erfüllt. Wenn du Einwände hast gerne Melden.  👍  @FlorianMihm

**Comment by FlorianMihm** [comment]
@Eyyuep Alles perfekt umgesetzt. Saubere Arbeit. Bei mir läuft alles super und die Fehler werden korrekt ausgegeben.
Einen habe ich aber noch gefunden [IOException](https://github.com/Eyyuep/DBsync/blob/5dd310b1b78f6e5fe2934d77ad734fe3d0eace68/src/main/java/de/praktikant/Start.java#L25). Danach ist das Issue fertig ;)

**Comment by nartesh** [comment]
@FlorianMihm IOException wurde erledigt ;)
