### ISSUE TITLE
String.format() statt String Konktatination einsetzen

### ISSUE THREAD

**Issue by TobiasSMI** [Eyyuep/DBsync#3]
Bitte tauscht alle Strings aus, in denen ihr String Konkatenation einsetzt, **gegen String.format()**

Hier ein Beispiel für String.format()
https://beginnersbook.com/2017/10/java-string-format-method/#:~:text=A%20Simple%20Example%20of%20Java%20String%20format()%20method

hier ein Beispiel für String Konkatenation
https://github.com/Eyyuep/DBsync/blob/4ac7d13a2247aad6a9dfba90f47911bc59cb730a/src/main/java/de/praktikant/Main.java#L42

**Comment by nartesh** [comment]
String.format() fast erledigt. Es fehlt nur die 2 Zeile für die DB Verbindung

**Comment by nartesh** [comment]
Tobias, wir sind zu weit fertig. Kannst du nochmal darüber schauen, bevor wir Issues schließen? Danke!

**Comment by TobiasSMI** [comment]
Hallo @nartesh , kannst du mir bitte die Zeilen oder Commits verlinken, in denen ihr auf String.format setzt, statt String concat?

**Comment by nartesh** [comment]
Die 2 Zeilen sie auskommentiert sind, ist unseren Versuch, aber funktioniert nicht.
Die untere 2 Zeilen sind in Moment so geblieben, aber ohne string.format. Wie können wir die beiden in string.format umwandeln?

![Screenshot 2022-11-25 091936](https://user-images.githubusercontent.com/74494162/203934082-452ba2a8-f4e3-45e7-8e13-24e21b3ca3bc.png)

**Comment by TobiasSMI** [comment]
Wieso habt ihr die Leerzeichen zwischen eurem Text und den %s gesetzt? Die werden vom String format mit übernommen und dann hat ihr keine korrekte jdbc URL mehr.

Welcher Fehler wird euch ausgegeben, habt ihr euch die String mit dem Debugger angesehen? Wenn ja, poste mal den Inhalt der Variable an dem Breakpoint bzw. den Fehler, der euch ausgegeben wird.

**Comment by nartesh** [comment]
Danke Tobias! Das Problem wurde gelöst!
