### ISSUE TITLE
Variable Namen konventionen

### ISSUE THREAD

**Issue by Gromidev** [Eyyuep/DBsync#30]
Variablen sollten einheitlich benannt werden.

@TobiasSMI sollen wir die alle englische oder deutsche Namen geben

**Comment by TobiasSMI** [comment]
Das dürft ihr für euch im Team entscheiden.
Ich selbst nutze meist englische Bezeichner (da oft aus Ressourcen von eng. Autoren abgekupfert wird und man die dortigen Variablen dann nicht groß umbenennen muss ;) )

**Comment by Eyyuep** [comment]
Wir haben mit dem Commit ac4d3de4505b01bac51e7d7f27eab58ced33a6e9, die Anmerkung von @Gromidev erfüllt. 👍
