### ISSUE TITLE
showDB behalten?

### ISSUE THREAD

**Issue by nartesh** [Eyyuep/DBsync#32]
@TobiasSMI, brauchen wir die auskommentierte Methode showDB noch?

https://github.com/Eyyuep/DBsync/blob/ac4d3de4505b01bac51e7d7f27eab58ced33a6e9/src/main/java/de/praktikant/Start.java#L59-L69

**Comment by TobiasSMI** [comment]
- Wie lange ist die Funktion bereits auskommentiert?
- musstet ihr die Funktionen zwischenzeitlich einkommentieren, um etwas lauffähig zu bekommen?

**Comment by Eyyuep** [comment]
@TobiasSMI Der Auftrag war ja 	"_**Ich benötige ein Tool, welches Kurzgesagt, 2 Datenbanken miteinander vergleicht und Differenzen meldet.**_", welches bereits besteht und die ShowDB.java war nur als Debug Funktion für uns Wichtig und daher wurde die ShowDB auskommentiert vor  den Tests.

Sofern der zukünftige User die Daten auslesen möchte wäre eine Methode bereits implemtiert.

Ich kann die Methode auch ganz löschen, wenn kein Bedarf besteht.

**Comment by TobiasSMI** [comment]
wenn die Methode nicht benötigt wird, wäre es sinnvoll diese zu entfernen.

**Comment by Eyyuep** [comment]
@TobiasSMI Alles klar, Danke 👍

**Comment by Eyyuep** [comment]
d944863977d72862d43b7e3b49e8b0aed9e05ec4 Update Start.Java bzw. entfernen des Code blocks✅ 

3a6a0e8ca149319c5525e8d48b13705553d0a7e9 Delete ShowDB.Java ✅ 

Vielen dank für dein Feedback @TobiasSMI.
