### ISSUE TITLE
IDE Warnungen beachten - hier: SQL Exception abfangen

### ISSUE THREAD

**Issue by TobiasSMI** [Eyyuep/DBsync#4]
https://github.com/Eyyuep/DBsync/blob/4ac7d13a2247aad6a9dfba90f47911bc59cb730a/src/main/java/de/praktikant/Main.java#L43

in dem Schnipsel oben ruft ihr showDB auf. Diese Methode kann potenziell eine NullPointerException werfen, diese lasst ihr über die Mainmethodensignatur den Aufrufer werfen.

Besser wäre:
Methodenaufrufe in einen Try Catch zu verpacken und auf eine Exception (mindestens) mit einer log Ausgabe zu reagieren, siehe hierzu auch #2 

https://docs.oracle.com/javase/tutorial/essential/exceptions/tryResourceClose.html#:~:text=%7D%20catch%20(SQLException%20e)%20%7B

**Comment by nartesh** [comment]
Methoden in Try-Catch block implementiert.
