### ISSUE TITLE
Issues erzeugen

### ISSUE THREAD

**Issue by TobiasSMI** [Eyyuep/DBsync#5]
Hi @Gromidev  
Wir haben am Mittwoch kurz besprochen, dass das Programm noch weiter modularisiert werden soll. Aktuell ist alles static und in der Main Methode, was so ja nicht dauerhaft bleiben sollte.

Bitte erzeuge zusätzliche Issues für jede technische Schuld, die ihr euch im Laufe der Entwicklungssessions aufladet. Bisher ist, anders als wir das besprochen haben, noch kein einziges Issue in Github erzeugt worden!
Issues die mir da auf Anhieb einfallen wären:

**_nach Lauffähigkeit des Programms und ausräumen der groben technischen Schnitzer_** 

- [x] Erstellung und Übertrag nach Spring boot
- [x] Code formatieren
- [x] auskommentierten Code entfernen
> - [x] Tests hinzufügen
> - [x] kann in die DB geschrieben werden? 
> - [x] Komme ich an einen Datensatz heran? 
> - [x] werden 2 Werte korrekt verglichen über meine compareData Methode?

Wenn die Issues erzeugt wurden, kann das Ticket geschlossen werden.

**Comment by nartesh** [comment]
Erstellung und Übertrag nach Spring Boot wurde als new Issue erstellt.
