### ISSUE TITLE
readme.MD File hinzufügen und Projekt beschreiben

### ISSUE THREAD

**Issue by TobiasSMI** [Eyyuep/DBsync#6]
**Bitte folgende Struktur in der Readme einbetten und die Punkte beschreiben**

- [x] 1) Info über das Projekt
- [x] 2) Verwendete Werkzeuge, Tools etc.
- [x] 3) Getting Started
- [x] a) Voraussetzungen
- [x] b) Installation
- [x] 4) Roadmap (@Gromidev da müsstest du doch direkt etwas eintragen können)
- [x] 5) Acknowledgments (hier bitte Links, Ressource, etc einfügen, die ihr hilfreich fandet und eine Erwähnung verdient haben, Beispiel: https://choosealicense.com/ -> eine super Quelle für eine probate Lizenz Auswahl )

**Comment by Eyyuep** [comment]
Hey @TobiasSMI, wir haben die Punkte 1-2 und 5 soweit fertig und bräuchten vielleicht noch ein paar Tipps bei den Punkten 3a und 3b. 

Bei dem Punkten 3a und 3b wissen wir nicht wie sehr wir in Detail gehen müssen oder nicht müssen.

**Comment by TobiasSMI** [comment]
@Eyyuep stell dir vor, du willst deinem Dad dein Programm zeigen. Es also wirklich bei ihm laufen lassen. Was muss er vorab haben / installieren, um dies zu bewerkstelligen (ein Start über die IDE soll dabei nicht erläutert werden, sondern der Start über die CMD / Bash des Users, in etwa nach diesem Muster: https://stackoverflow.com/questions/16137713/how-do-i-run-a-java-program-from-the-command-line-on-windows)

Was mir dabei sofort in den Sinn kommt sind, welches JDK ist vorab zu installieren, muss man evtl. Umgebungsvariablen setzen usw.

Dies könnt ihr am einfachsten testen, in dem ihr euch eine leere VM nehmt, und euer Programm dort startet. Was ist nun alles nötig, damit ihr es dort starten lassen konntet? Welche Befehle musstet ihr ausführen?

**Comment by Eyyuep** [comment]
Hey @TobiasSMI, 

wir haben das wie du wolltest testweise auf einer VM zum laufen gebracht und wollten es über die CMD/GIT Bash auch ausführen, aber leider kann die Main.java nicht auf andere Java-Dateien zugreifen und die db.config.properties wird gänzlich ignoriert. Wir versuchen es nochmal alleine eigenständig es zum laufen zubringen und melden uns nochmal gegebenfalls bei dir, wenn es nicht klappt.

**Comment by TobiasSMI** [comment]
Alles klar, das war nur ein Beispiel, wie ihr die Steps festhalten könnt für eure Doku. Dass das Programm nicht läuft ist ein neues Issue, bitte daher ein neues Issue eröffnen.

Diese Aufgabe hier ist gemäß dem Titel zu bearbeiten.

Man verliert sonst den Überblick bei einer Durchmischung der Aufgaben/Todos.

Danke für das Update @Eyyuep

**Comment by nartesh** [comment]
Roadmap macht keinen Sinn mehr und wurde abgebrochen (nach Gespräch zwischen @Gromidev  und @TobiasSMI).
